document.addEventListener("DOMContentLoaded", function() {
    // Map of countries to their respective time zones. Attribute values are withiin ""
    const countryTimeZones = {
       
    "us": "America/New_York",
    "uk": "Europe/London",
    "india": "Asia/Kolkata",
    "australia": "Australia/Sydney",
    "japan": "Asia/Tokyo",
    "canada": "America/Toronto",
    "germany": "Europe/Berlin",
    "france": "Europe/Paris",
    "china": "Asia/Shanghai",
    "brazil": "America/Sao_Paulo",
    "sa": "Africa/Johannesburg",
    "russia": "Europe/Moscow",
    "mexico": "America/Mexico_City",
    "italy": "Europe/Rome",
    "spain": "Europe/Madrid",
    "sk": "Asia/Seoul",
    "saudi": "Asia/Riyadh",
    "argentina": "America/Argentina/Buenos_Aires",
    "nigeria": "Africa/Lagos",
    "turkey": "Europe/Istanbul",
    "indonesia": "Asia/Jakarta",
    "netherlands": "Europe/Amsterdam",
    "sweden": "Europe/Stockholm",
    "switzerland": "Europe/Zurich",
    "afghanistan": "Asia/Kabul",
    "albania": "Europe/Tirane",
    "algeria": "Africa/Algiers",
    "andorra": "Europe/Andorra",
    "angola": "Africa/Luanda",
    "antigua": "America/Antigua",
    "armenia": "Asia/Yerevan",
    "aruba": "America/Aruba",
    "austria": "Europe/Vienna",
    "azerbaijan": "Asia/Baku",
    "bahamas": "America/Nassau",
    "bahrain": "Asia/Bahrain",
    "bangladesh": "Asia/Dhaka",
    "barbados": "America/Barbados",
    "belarus": "Europe/Minsk",
    "belgium": "Europe/Brussels",
    "belize": "America/Belize",
    "benin": "Africa/Porto-Novo",
    "bhutan": "Asia/Thimphu",
    "bolivia": "America/La_Paz",
    "bosnia": "Europe/Sarajevo",
    "botswana": "Africa/Gaborone",
    "brunei": "Asia/Brunei",
    "bulgaria": "Europe/Sofia",
    "burkina": "Africa/Ouagadougou",
    "burundi": "Africa/Bujumbura",
    "cambodia": "Asia/Phnom_Penh",
    "cameroon": "Africa/Douala",
    "cape": "Atlantic/Cape_Verde",
    "central": "Africa/Bangui",
    "chad": "Africa/Ndjamena",
    "chile": "America/Santiago",
    "colombia": "America/Bogota",
    "comoros": "Indian/Comoro",
    "costa": "America/Costa_Rica",
    "croatia": "Europe/Zagreb",
    "cuba": "America/Havana",
    "cyprus": "Asia/Nicosia",
    "czech": "Europe/Prague",
    "democratic": "Africa/Kinshasa",
    "denmark": "Europe/Copenhagen",
    "djibouti": "Africa/Djibouti",
    "dominica": "America/Dominica",
    "dominican": "America/Santo_Domingo",
    "ecuador": "America/Guayaquil",
    "egypt": "Africa/Cairo",
    "el": "America/El_Salvador",
    "equatorial": "Africa/Malabo",
    "eritrea": "Africa/Asmara",
    "estonia": "Europe/Tallinn",
    "eswatini": "Africa/Mbabane",
    "ethiopia": "Africa/Addis_Ababa",
    "fiji": "Pacific/Fiji",
    "finland": "Europe/Helsinki",
    "gabon": "Africa/Libreville",
    "gambia": "Africa/Banjul",
    "georgia": "Asia/Tbilisi",
    "ghana": "Africa/Accra",
    "greece": "Europe/Athens",
    "grenada": "America/Grenada",
    "guatemala": "America/Guatemala",
    "guinea": "Africa/Conakry",
    "gnb": "Africa/Bissau",
    "guyana": "America/Guyana",
    "haiti": "America/Port-au-Prince",
    "honduras": "America/Tegucigalpa",
    "hungary": "Europe/Budapest",
    "iceland": "Atlantic/Reykjavik",
    "iran": "Asia/Tehran",
    "iraq": "Asia/Baghdad",
    "ireland": "Europe/Dublin",
    "israel": "Asia/Jerusalem",
    "jamaica": "America/Jamaica",
    "jordan": "Asia/Amman",
    "kazakhstan": "Asia/Almaty",
    "kenya": "Africa/Nairobi",
    "kiribati": "Pacific/Tarawa",
    "kosovo": "Europe/Belgrade",
    "kuwait": "Asia/Kuwait",
    "kyrgyzstan": "Asia/Bishkek",
    "laos": "Asia/Vientiane",
    "latvia": "Europe/Riga",
    "lebanon": "Asia/Beirut",
    "lesotho": "Africa/Maseru",
    "liberia": "Africa/Monrovia",
    "libya": "Africa/Tripoli",
    "liechtenstein": "Europe/Vaduz",
    "lithuania": "Europe/Vilnius",
    "luxembourg": "Europe/Luxembourg",
    "madagascar": "Indian/Antananarivo",
    "malawi": "Africa/Blantyre",
    "malaysia": "Asia/Kuala_Lumpur",
    "maldives": "Indian/Maldives",
    "mali": "Africa/Bamako",
    "malta": "Europe/Malta",
    "marshall": "Pacific/Majuro",
    "mauritania": "Africa/Nouakchott",
    "mauritius": "Indian/Mauritius",
    "micronesia": "Pacific/Pohnpei",
    "moldova": "Europe/Chisinau",
    "monaco": "Europe/Monaco",
    "mongolia": "Asia/Ulaanbaatar",
    "montenegro": "Europe/Podgorica",
    "morocco": "Africa/Casablanca",
    "mozambique": "Africa/Maputo",
    "myanmar": "Asia/Yangon",
    "namibia": "Africa/Windhoek",
    "nauru": "Pacific/Nauru",
    "nepal": "Asia/Kathmandu",
    "nz": "Pacific/Auckland",
    "nicaragua": "America/Managua",
    "niger": "Africa/Niamey",
    "north": "Europe/Skopje",
    "norway": "Europe/Oslo",
    "oman": "Asia/Muscat",
    "pakistan": "Asia/Karachi",
    "palau": "Pacific/Palau",
    "palestine": "Asia/Gaza",
    "panama": "America/Panama",
    "papua": "Pacific/Port_Moresby",
    "paraguay": "America/Asuncion",
    "peru": "America/Lima",
    "philippines": "Asia/Manila",
    "poland": "Europe/Warsaw",
    "portugal": "Europe/Lisbon",
    "qatar": "Asia/Qatar",
    "republic": "Africa/Brazzaville",
    "romania": "Europe/Bucharest",
    "rwanda": "Africa/Kigali",
    "saint": "America/St_Kitts",
    "lucia": "America/St_Lucia",
    "vincent": "America/St_Vincent",
    "samoa": "Pacific/Apia",
    "san": "Europe/San_Marino",
    "stp": "Africa/Sao_Tome",
    "senegal": "Africa/Dakar",
    "serbia": "Europe/Belgrade",
    "seychelles": "Indian/Mahe",
    "sierra": "Africa/Freetown",
    "singapore": "Asia/Singapore",
    "slovakia": "Europe/Bratislava",
    "slovenia": "Europe/Ljubljana",
    "solomon": "Pacific/Guadalcanal",
    "somalia": "Africa/Mogadishu",
    "lanka": "Asia/Colombo",
    "sudan": "Africa/Khartoum",
    "suriname": "America/Paramaribo",
    "syria": "Asia/Damascus",
    "taiwan": "Asia/Taipei",
    "tajikistan": "Asia",
    "tajikistan": "Asia/Dushanbe",
    "tanzania": "Africa/Dar_es_Salaam",
    "thailand": "Asia/Bangkok",
    "tls": "Asia/Dili",
    "togo": "Africa/Lome",
    "tonga": "Pacific/Tongatapu",
    "tto": "America/Port_of_Spain",
    "tunisia": "Africa/Tunis",
    "turkmenistan": "Asia/Ashgabat",
    "tuvalu": "Pacific/Funafuti",
    "uganda": "Africa/Kampala",
    "ukraine": "Europe/Kiev",
    "uae": "Asia/Dubai",
    "uruguay": "America/Montevideo",
    "uzbekistan": "Asia/Tashkent",
    "vanuatu": "Pacific/Efate",
    "vatican": "Europe/Vatican",
    "venezuela": "America/Caracas",
    "vietnam": "Asia/Ho_Chi_Minh",
    "yemen": "Asia/Aden",
    "zambia": "Africa/Lusaka",
    "zimbabwe": "Africa/Harare"


    };

    // Function to update time for all elements with nw-time attribute
    const updateTime = () => {
        const elements = document.querySelectorAll('[nw-time]');
        elements.forEach(element => {
            const country = element.getAttribute('nw-time');
            const timeZone = countryTimeZones[country];

            if (timeZone) {
                const options = {
                    timeZone: timeZone,
                    hour12: true,
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit'
                };
                const now = new Date();
                const timeString = now.toLocaleTimeString('en-US', options);
                element.textContent = timeString;
            } else {
                element.textContent = "Time zone not found";
            }
        });
    };

    // Initial update
    updateTime();
    // Update time every second
    setInterval(updateTime, 1000);
});
